[2021-04-12T14:04:44.067233-04:00] php.DEBUG: Warning: include(/var/www/symfony/reportes/var/cache/de_/App_KernelDevDebugContainer.php): failed to open stream: No such file or directory {"exception":{"Symfony\\Component\\ErrorHandler\\Exception\\SilencedErrorContext":{"severity":2,"file":"/var/www/symfony/reportes/vendor/symfony/http-kernel/Kernel.php","line":469,"trace":[{"file":"/var/www/symfony/reportes/vendor/symfony/http-kernel/Kernel.php","line":469,"function":"include"}],"count":1}}} []
[2021-04-12T14:04:44.080568-04:00] php.DEBUG: Warning: include(): Failed opening '/var/www/symfony/reportes/var/cache/de_/App_KernelDevDebugContainer.php' for inclusion (include_path='.:/usr/share/php') [] []
[2021-04-22T16:06:41.646918-04:00] request.INFO: Matched route "home". {"route":"home","route_parameters":{"_route":"home","_controller":"App\\Controller\\DashBoardController::index"},"request_uri":"https://192.168.1.16:8004/","method":"GET"} []
[2021-04-22T16:06:41.694851-04:00] security.INFO: Populated the TokenStorage with an anonymous Token. [] []
[2021-04-22T16:06:41.739938-04:00] security.DEBUG: Access denied, the user is not fully authenticated; redirecting to authentication entry point. {"exception":"[object] (Symfony\\Component\\Security\\Core\\Exception\\AccessDeniedException(code: 403): Access Denied. at /var/www/symfony/reportes/vendor/symfony/security-http/Firewall/AccessListener.php:106)"} []
[2021-04-22T16:06:41.740640-04:00] security.DEBUG: Calling Authentication entry point. [] []
[2021-04-22T16:06:41.895405-04:00] request.INFO: Matched route "app_login". {"route":"app_login","route_parameters":{"_route":"app_login","_controller":"App\\Controller\\SecurityController::login"},"request_uri":"https://192.168.1.16:8004/login","method":"GET"} []
[2021-04-22T16:06:41.918351-04:00] security.INFO: Populated the TokenStorage with an anonymous Token. [] []
[2021-04-22T16:06:42.054873-04:00] request.INFO: Matched route "_wdt". {"route":"_wdt","route_parameters":{"_route":"_wdt","_controller":"web_profiler.controller.profiler::toolbarAction","token":"00f768"},"request_uri":"https://192.168.1.16:8004/_wdt/00f768","method":"GET"} []
[2021-04-22T16:06:42.164703-04:00] request.ERROR: Uncaught PHP Exception Symfony\Component\HttpKernel\Exception\NotFoundHttpException: "No route found for "GET /favicon.ico" (from "https://192.168.1.16:8004/login")" at /var/www/symfony/reportes/vendor/symfony/http-kernel/EventListener/RouterListener.php line 136 {"exception":"[object] (Symfony\\Component\\HttpKernel\\Exception\\NotFoundHttpException(code: 0): No route found for \"GET /favicon.ico\" (from \"https://192.168.1.16:8004/login\") at /var/www/symfony/reportes/vendor/symfony/http-kernel/EventListener/RouterListener.php:136)\n[previous exception] [object] (Symfony\\Component\\Routing\\Exception\\ResourceNotFoundException(code: 0): No routes found for \"/favicon.ico/\". at /var/www/symfony/reportes/vendor/symfony/routing/Matcher/Dumper/CompiledUrlMatcherTrait.php:70)"} []
[2021-04-22T16:06:49.494864-04:00] request.INFO: Matched route "app_login". {"route":"app_login","route_parameters":{"_route":"app_login","_controller":"App\\Controller\\SecurityController::login"},"request_uri":"https://192.168.1.16:8004/login","method":"POST"} []
[2021-04-22T16:06:49.665987-04:00] doctrine.DEBUG: SELECT t0.id AS id_1, t0.email AS email_2, t0.roles AS roles_3, t0.password AS password_4, t0.nombre AS nombre_5, t0.apellidos AS apellidos_6, t0.activo AS activo_7, t0.fecha_alta AS fecha_alta_8, t0.fecha_update AS fecha_update_9, t0.telef AS telef_10, t0.descripcion AS descripcion_11, t0.ocupacion AS ocupacion_12, t0.usertype AS usertype_13 FROM user t0 WHERE t0.email = ? LIMIT 1 ["prueba"] []
[2021-04-22T16:06:49.979517-04:00] php.DEBUG: Warning: ldap_bind(): Unable to bind to server: Invalid credentials {"exception":{"Symfony\\Component\\ErrorHandler\\Exception\\SilencedErrorContext":{"severity":2,"file":"/var/www/symfony/reportes/vendor/symfony/ldap/Adapter/ExtLdap/Connection.php","line":72,"trace":[{"file":"/var/www/symfony/reportes/vendor/symfony/ldap/Ldap.php","line":40,"function":"bind","class":"Symfony\\Component\\Ldap\\Adapter\\ExtLdap\\Connection","type":"->"}],"count":1}}} []
[2021-04-22T16:06:49.981171-04:00] doctrine.DEBUG: SELECT t0.id AS id_1, t0.email AS email_2, t0.roles AS roles_3, t0.password AS password_4, t0.nombre AS nombre_5, t0.apellidos AS apellidos_6, t0.activo AS activo_7, t0.fecha_alta AS fecha_alta_8, t0.fecha_update AS fecha_update_9, t0.telef AS telef_10, t0.descripcion AS descripcion_11, t0.ocupacion AS ocupacion_12, t0.usertype AS usertype_13 FROM user t0 WHERE t0.email = ? LIMIT 1 ["prueba"] []
[2021-04-22T16:06:49.983083-04:00] security.INFO: Authentication request failed. {"exception":"[object] (Symfony\\Component\\Security\\Core\\Exception\\BadCredentialsException(code: 0): Bad credentials. at /var/www/symfony/reportes/vendor/symfony/security-core/Authentication/Provider/UserAuthenticationProvider.php:67)\n[previous exception] [object] (Symfony\\Component\\Security\\Core\\Exception\\UsernameNotFoundException(code: 0): There is no user with name \"prueba\". at /var/www/symfony/reportes/vendor/symfony/security-core/User/ChainUserProvider.php:62)"} []
[2021-04-22T16:06:49.983330-04:00] security.DEBUG: Authentication failure, redirect triggered. {"failure_path":"app_login"} []
[2021-04-22T16:06:50.041733-04:00] request.INFO: Matched route "app_login". {"route":"app_login","route_parameters":{"_route":"app_login","_controller":"App\\Controller\\SecurityController::login"},"request_uri":"https://192.168.1.16:8004/login","method":"GET"} []
[2021-04-22T16:06:50.048112-04:00] security.INFO: Populated the TokenStorage with an anonymous Token. [] []
[2021-04-22T16:06:50.249181-04:00] request.INFO: Matched route "_wdt". {"route":"_wdt","route_parameters":{"_route":"_wdt","_controller":"web_profiler.controller.profiler::toolbarAction","token":"8ac81c"},"request_uri":"https://192.168.1.16:8004/_wdt/8ac81c","method":"GET"} []
[2021-04-22T16:07:09.297733-04:00] request.INFO: Matched route "app_login". {"route":"app_login","route_parameters":{"_route":"app_login","_controller":"App\\Controller\\SecurityController::login"},"request_uri":"https://192.168.1.16:8004/login","method":"POST"} []
[2021-04-22T16:07:09.314011-04:00] doctrine.DEBUG: SELECT t0.id AS id_1, t0.email AS email_2, t0.roles AS roles_3, t0.password AS password_4, t0.nombre AS nombre_5, t0.apellidos AS apellidos_6, t0.activo AS activo_7, t0.fecha_alta AS fecha_alta_8, t0.fecha_update AS fecha_update_9, t0.telef AS telef_10, t0.descripcion AS descripcion_11, t0.ocupacion AS ocupacion_12, t0.usertype AS usertype_13 FROM user t0 WHERE t0.email = ? LIMIT 1 ["yuriang"] []
[2021-04-22T16:07:09.331124-04:00] php.DEBUG: Warning: ldap_bind(): Unable to bind to server: Invalid credentials {"exception":{"Symfony\\Component\\ErrorHandler\\Exception\\SilencedErrorContext":{"severity":2,"file":"/var/www/symfony/reportes/vendor/symfony/ldap/Adapter/ExtLdap/Connection.php","line":72,"trace":[{"file":"/var/www/symfony/reportes/vendor/symfony/ldap/Ldap.php","line":40,"function":"bind","class":"Symfony\\Component\\Ldap\\Adapter\\ExtLdap\\Connection","type":"->"}],"count":1}}} []
[2021-04-22T16:07:09.331719-04:00] doctrine.DEBUG: SELECT t0.id AS id_1, t0.email AS email_2, t0.roles AS roles_3, t0.password AS password_4, t0.nombre AS nombre_5, t0.apellidos AS apellidos_6, t0.activo AS activo_7, t0.fecha_alta AS fecha_alta_8, t0.fecha_update AS fecha_update_9, t0.telef AS telef_10, t0.descripcion AS descripcion_11, t0.ocupacion AS ocupacion_12, t0.usertype AS usertype_13 FROM user t0 WHERE t0.email = ? LIMIT 1 ["yuriang"] []
[2021-04-22T16:07:09.333449-04:00] security.INFO: Authentication request failed. {"exception":"[object] (Symfony\\Component\\Security\\Core\\Exception\\BadCredentialsException(code: 0): Bad credentials. at /var/www/symfony/reportes/vendor/symfony/security-core/Authentication/Provider/UserAuthenticationProvider.php:67)\n[previous exception] [object] (Symfony\\Component\\Security\\Core\\Exception\\UsernameNotFoundException(code: 0): There is no user with name \"yuriang\". at /var/www/symfony/reportes/vendor/symfony/security-core/User/ChainUserProvider.php:62)"} []
[2021-04-22T16:07:09.333711-04:00] security.DEBUG: Authentication failure, redirect triggered. {"failure_path":"app_login"} []
[2021-04-22T16:07:09.390035-04:00] request.INFO: Matched route "app_login". {"route":"app_login","route_parameters":{"_route":"app_login","_controller":"App\\Controller\\SecurityController::login"},"request_uri":"https://192.168.1.16:8004/login","method":"GET"} []
[2021-04-22T16:07:09.396846-04:00] security.INFO: Populated the TokenStorage with an anonymous Token. [] []
[2021-04-22T16:07:09.580179-04:00] request.INFO: Matched route "_wdt". {"route":"_wdt","route_parameters":{"_route":"_wdt","_controller":"web_profiler.controller.profiler::toolbarAction","token":"876dc2"},"request_uri":"https://192.168.1.16:8004/_wdt/876dc2","method":"GET"} []
[2021-04-22T16:07:25.488853-04:00] request.INFO: Matched route "app_login". {"route":"app_login","route_parameters":{"_route":"app_login","_controller":"App\\Controller\\SecurityController::login"},"request_uri":"https://192.168.1.16:8004/login","method":"POST"} []
[2021-04-22T16:07:25.510381-04:00] doctrine.DEBUG: SELECT t0.id AS id_1, t0.email AS email_2, t0.roles AS roles_3, t0.password AS password_4, t0.nombre AS nombre_5, t0.apellidos AS apellidos_6, t0.activo AS activo_7, t0.fecha_alta AS fecha_alta_8, t0.fecha_update AS fecha_update_9, t0.telef AS telef_10, t0.descripcion AS descripcion_11, t0.ocupacion AS ocupacion_12, t0.usertype AS usertype_13 FROM user t0 WHERE t0.email = ? LIMIT 1 ["yuriang"] []
[2021-04-22T16:07:25.528695-04:00] php.DEBUG: Warning: ldap_bind(): Unable to bind to server: Invalid credentials {"exception":{"Symfony\\Component\\ErrorHandler\\Exception\\SilencedErrorContext":{"severity":2,"file":"/var/www/symfony/reportes/vendor/symfony/ldap/Adapter/ExtLdap/Connection.php","line":72,"trace":[{"file":"/var/www/symfony/reportes/vendor/symfony/ldap/Ldap.php","line":40,"function":"bind","class":"Symfony\\Component\\Ldap\\Adapter\\ExtLdap\\Connection","type":"->"}],"count":1}}} []
[2021-04-22T16:07:25.529487-04:00] doctrine.DEBUG: SELECT t0.id AS id_1, t0.email AS email_2, t0.roles AS roles_3, t0.password AS password_4, t0.nombre AS nombre_5, t0.apellidos AS apellidos_6, t0.activo AS activo_7, t0.fecha_alta AS fecha_alta_8, t0.fecha_update AS fecha_update_9, t0.telef AS telef_10, t0.descripcion AS descripcion_11, t0.ocupacion AS ocupacion_12, t0.usertype AS usertype_13 FROM user t0 WHERE t0.email = ? LIMIT 1 ["yuriang"] []
[2021-04-22T16:07:25.531334-04:00] security.INFO: Authentication request failed. {"exception":"[object] (Symfony\\Component\\Security\\Core\\Exception\\BadCredentialsException(code: 0): Bad credentials. at /var/www/symfony/reportes/vendor/symfony/security-core/Authentication/Provider/UserAuthenticationProvider.php:67)\n[previous exception] [object] (Symfony\\Component\\Security\\Core\\Exception\\UsernameNotFoundException(code: 0): There is no user with name \"yuriang\". at /var/www/symfony/reportes/vendor/symfony/security-core/User/ChainUserProvider.php:62)"} []
[2021-04-22T16:07:25.531591-04:00] security.DEBUG: Authentication failure, redirect triggered. {"failure_path":"app_login"} []
[2021-04-22T16:07:25.596567-04:00] request.INFO: Matched route "app_login". {"route":"app_login","route_parameters":{"_route":"app_login","_controller":"App\\Controller\\SecurityController::login"},"request_uri":"https://192.168.1.16:8004/login","method":"GET"} []
[2021-04-22T16:07:25.603697-04:00] security.INFO: Populated the TokenStorage with an anonymous Token. [] []
[2021-04-22T16:07:25.767994-04:00] request.INFO: Matched route "_wdt". {"route":"_wdt","route_parameters":{"_route":"_wdt","_controller":"web_profiler.controller.profiler::toolbarAction","token":"7819ed"},"request_uri":"https://192.168.1.16:8004/_wdt/7819ed","method":"GET"} []
[2021-06-04T12:10:10.629252-04:00] request.INFO: Matched route "home". {"route":"home","route_parameters":{"_route":"home","_controller":"App\\Controller\\DashBoardController::index"},"request_uri":"https://192.168.1.16:8004/","method":"GET"} []
[2021-06-04T12:10:17.764650-04:00] security.INFO: Populated the TokenStorage with an anonymous Token. [] []
[2021-06-04T12:10:24.631939-04:00] security.DEBUG: Access denied, the user is not fully authenticated; redirecting to authentication entry point. {"exception":"[object] (Symfony\\Component\\Security\\Core\\Exception\\AccessDeniedException(code: 403): Access Denied. at /var/www/symfony/reportes/vendor/symfony/security-http/Firewall/AccessListener.php:106)"} []
[2021-06-04T12:10:24.667006-04:00] security.DEBUG: Calling Authentication entry point. [] []
[2021-06-04T12:10:34.603108-04:00] request.INFO: Matched route "app_login". {"route":"app_login","route_parameters":{"_route":"app_login","_controller":"App\\Controller\\SecurityController::login"},"request_uri":"https://192.168.1.16:8004/login","method":"GET"} []
[2021-06-04T12:10:36.992375-04:00] security.INFO: Populated the TokenStorage with an anonymous Token. [] []
[2021-06-04T12:10:38.210940-04:00] request.INFO: Matched route "_wdt". {"route":"_wdt","route_parameters":{"_route":"_wdt","_controller":"web_profiler.controller.profiler::toolbarAction","token":"983cc8"},"request_uri":"https://192.168.1.16:8004/_wdt/983cc8","method":"GET"} []
[2021-06-04T12:10:38.365947-04:00] request.ERROR: Uncaught PHP Exception Symfony\Component\HttpKernel\Exception\NotFoundHttpException: "No route found for "GET /favicon.ico" (from "https://192.168.1.16:8004/login")" at /var/www/symfony/reportes/vendor/symfony/http-kernel/EventListener/RouterListener.php line 136 {"exception":"[object] (Symfony\\Component\\HttpKernel\\Exception\\NotFoundHttpException(code: 0): No route found for \"GET /favicon.ico\" (from \"https://192.168.1.16:8004/login\") at /var/www/symfony/reportes/vendor/symfony/http-kernel/EventListener/RouterListener.php:136)\n[previous exception] [object] (Symfony\\Component\\Routing\\Exception\\ResourceNotFoundException(code: 0): No routes found for \"/favicon.ico/\". at /var/www/symfony/reportes/vendor/symfony/routing/Matcher/Dumper/CompiledUrlMatcherTrait.php:70)"} []
[2021-06-04T12:16:36.989247-04:00] request.INFO: Matched route "app_login". {"route":"app_login","route_parameters":{"_route":"app_login","_controller":"App\\Controller\\SecurityController::login"},"request_uri":"https://192.168.1.16:8004/login","method":"POST"} []
[2021-06-04T12:16:37.741572-04:00] doctrine.DEBUG: SELECT t0.id AS id_1, t0.email AS email_2, t0.roles AS roles_3, t0.password AS password_4, t0.nombre AS nombre_5, t0.apellidos AS apellidos_6, t0.activo AS activo_7, t0.fecha_alta AS fecha_alta_8, t0.fecha_update AS fecha_update_9, t0.telef AS telef_10, t0.descripcion AS descripcion_11, t0.ocupacion AS ocupacion_12, t0.usertype AS usertype_13 FROM user t0 WHERE t0.email = ? LIMIT 1 ["yuriang"] []
[2021-06-04T12:16:38.325925-04:00] php.DEBUG: Warning: ldap_bind(): Unable to bind to server: Invalid credentials {"exception":{"Symfony\\Component\\ErrorHandler\\Exception\\SilencedErrorContext":{"severity":2,"file":"/var/www/symfony/reportes/vendor/symfony/ldap/Adapter/ExtLdap/Connection.php","line":72,"trace":[{"file":"/var/www/symfony/reportes/vendor/symfony/ldap/Ldap.php","line":40,"function":"bind","class":"Symfony\\Component\\Ldap\\Adapter\\ExtLdap\\Connection","type":"->"}],"count":1}}} []
[2021-06-04T12:16:38.362486-04:00] doctrine.DEBUG: SELECT t0.id AS id_1, t0.email AS email_2, t0.roles AS roles_3, t0.password AS password_4, t0.nombre AS nombre_5, t0.apellidos AS apellidos_6, t0.activo AS activo_7, t0.fecha_alta AS fecha_alta_8, t0.fecha_update AS fecha_update_9, t0.telef AS telef_10, t0.descripcion AS descripcion_11, t0.ocupacion AS ocupacion_12, t0.usertype AS usertype_13 FROM user t0 WHERE t0.email = ? LIMIT 1 ["yuriang"] []
[2021-06-04T12:16:38.364561-04:00] security.INFO: Authentication request failed. {"exception":"[object] (Symfony\\Component\\Security\\Core\\Exception\\BadCredentialsException(code: 0): Bad credentials. at /var/www/symfony/reportes/vendor/symfony/security-core/Authentication/Provider/UserAuthenticationProvider.php:67)\n[previous exception] [object] (Symfony\\Component\\Security\\Core\\Exception\\UsernameNotFoundException(code: 0): There is no user with name \"yuriang\". at /var/www/symfony/reportes/vendor/symfony/security-core/User/ChainUserProvider.php:62)"} []
[2021-06-04T12:16:38.364857-04:00] security.DEBUG: Authentication failure, redirect triggered. {"failure_path":"app_login"} []
[2021-06-04T12:16:38.430280-04:00] request.INFO: Matched route "app_login". {"route":"app_login","route_parameters":{"_route":"app_login","_controller":"App\\Controller\\SecurityController::login"},"request_uri":"https://192.168.1.16:8004/login","method":"GET"} []
[2021-06-04T12:16:38.436816-04:00] security.INFO: Populated the TokenStorage with an anonymous Token. [] []
[2021-06-04T12:16:38.820446-04:00] request.INFO: Matched route "_wdt". {"route":"_wdt","route_parameters":{"_route":"_wdt","_controller":"web_profiler.controller.profiler::toolbarAction","token":"871ed2"},"request_uri":"https://192.168.1.16:8004/_wdt/871ed2","method":"GET"} []
[2021-06-04T12:16:47.156742-04:00] request.INFO: Matched route "app_login". {"route":"app_login","route_parameters":{"_route":"app_login","_controller":"App\\Controller\\SecurityController::login"},"request_uri":"https://192.168.1.16:8004/login","method":"POST"} []
[2021-06-04T12:16:47.173177-04:00] doctrine.DEBUG: SELECT t0.id AS id_1, t0.email AS email_2, t0.roles AS roles_3, t0.password AS password_4, t0.nombre AS nombre_5, t0.apellidos AS apellidos_6, t0.activo AS activo_7, t0.fecha_alta AS fecha_alta_8, t0.fecha_update AS fecha_update_9, t0.telef AS telef_10, t0.descripcion AS descripcion_11, t0.ocupacion AS ocupacion_12, t0.usertype AS usertype_13 FROM user t0 WHERE t0.email = ? LIMIT 1 ["yuriang"] []
[2021-06-04T12:16:47.189401-04:00] php.DEBUG: Warning: ldap_bind(): Unable to bind to server: Invalid credentials {"exception":{"Symfony\\Component\\ErrorHandler\\Exception\\SilencedErrorContext":{"severity":2,"file":"/var/www/symfony/reportes/vendor/symfony/ldap/Adapter/ExtLdap/Connection.php","line":72,"trace":[{"file":"/var/www/symfony/reportes/vendor/symfony/ldap/Ldap.php","line":40,"function":"bind","class":"Symfony\\Component\\Ldap\\Adapter\\ExtLdap\\Connection","type":"->"}],"count":1}}} []
[2021-06-04T12:16:47.190025-04:00] doctrine.DEBUG: SELECT t0.id AS id_1, t0.email AS email_2, t0.roles AS roles_3, t0.password AS password_4, t0.nombre AS nombre_5, t0.apellidos AS apellidos_6, t0.activo AS activo_7, t0.fecha_alta AS fecha_alta_8, t0.fecha_update AS fecha_update_9, t0.telef AS telef_10, t0.descripcion AS descripcion_11, t0.ocupacion AS ocupacion_12, t0.usertype AS usertype_13 FROM user t0 WHERE t0.email = ? LIMIT 1 ["yuriang"] []
[2021-06-04T12:16:47.191850-04:00] security.INFO: Authentication request failed. {"exception":"[object] (Symfony\\Component\\Security\\Core\\Exception\\BadCredentialsException(code: 0): Bad credentials. at /var/www/symfony/reportes/vendor/symfony/security-core/Authentication/Provider/UserAuthenticationProvider.php:67)\n[previous exception] [object] (Symfony\\Component\\Security\\Core\\Exception\\UsernameNotFoundException(code: 0): There is no user with name \"yuriang\". at /var/www/symfony/reportes/vendor/symfony/security-core/User/ChainUserProvider.php:62)"} []
[2021-06-04T12:16:47.192069-04:00] security.DEBUG: Authentication failure, redirect triggered. {"failure_path":"app_login"} []
[2021-06-04T12:16:47.251403-04:00] request.INFO: Matched route "app_login". {"route":"app_login","route_parameters":{"_route":"app_login","_controller":"App\\Controller\\SecurityController::login"},"request_uri":"https://192.168.1.16:8004/login","method":"GET"} []
[2021-06-04T12:16:47.257889-04:00] security.INFO: Populated the TokenStorage with an anonymous Token. [] []
[2021-06-04T12:16:47.449054-04:00] request.INFO: Matched route "_wdt". {"route":"_wdt","route_parameters":{"_route":"_wdt","_controller":"web_profiler.controller.profiler::toolbarAction","token":"ea5b0f"},"request_uri":"https://192.168.1.16:8004/_wdt/ea5b0f","method":"GET"} []
[2021-06-04T14:12:59.031320-04:00] request.INFO: Matched route "home". {"route":"home","route_parameters":{"_route":"home","_controller":"App\\Controller\\DashBoardController::index"},"request_uri":"https://192.168.1.16:8004/","method":"GET"} []
[2021-06-04T14:12:59.076560-04:00] security.INFO: Populated the TokenStorage with an anonymous Token. [] []
[2021-06-04T14:12:59.139212-04:00] security.DEBUG: Access denied, the user is not fully authenticated; redirecting to authentication entry point. {"exception":"[object] (Symfony\\Component\\Security\\Core\\Exception\\AccessDeniedException(code: 403): Access Denied. at /var/www/symfony/reportes/vendor/symfony/security-http/Firewall/AccessListener.php:106)"} []
[2021-06-04T14:12:59.140117-04:00] security.DEBUG: Calling Authentication entry point. [] []
[2021-06-04T14:12:59.296338-04:00] request.INFO: Matched route "app_login". {"route":"app_login","route_parameters":{"_route":"app_login","_controller":"App\\Controller\\SecurityController::login"},"request_uri":"https://192.168.1.16:8004/login","method":"GET"} []
[2021-06-04T14:12:59.315034-04:00] security.INFO: Populated the TokenStorage with an anonymous Token. [] []
[2021-06-04T14:12:59.414483-04:00] request.INFO: Matched route "_wdt". {"route":"_wdt","route_parameters":{"_route":"_wdt","_controller":"web_profiler.controller.profiler::toolbarAction","token":"17b64f"},"request_uri":"https://192.168.1.16:8004/_wdt/17b64f","method":"GET"} []
[2021-06-04T14:12:59.542695-04:00] request.ERROR: Uncaught PHP Exception Symfony\Component\HttpKernel\Exception\NotFoundHttpException: "No route found for "GET /favicon.ico" (from "https://192.168.1.16:8004/login")" at /var/www/symfony/reportes/vendor/symfony/http-kernel/EventListener/RouterListener.php line 136 {"exception":"[object] (Symfony\\Component\\HttpKernel\\Exception\\NotFoundHttpException(code: 0): No route found for \"GET /favicon.ico\" (from \"https://192.168.1.16:8004/login\") at /var/www/symfony/reportes/vendor/symfony/http-kernel/EventListener/RouterListener.php:136)\n[previous exception] [object] (Symfony\\Component\\Routing\\Exception\\ResourceNotFoundException(code: 0): No routes found for \"/favicon.ico/\". at /var/www/symfony/reportes/vendor/symfony/routing/Matcher/Dumper/CompiledUrlMatcherTrait.php:70)"} []
[2021-06-04T14:14:38.549578-04:00] request.INFO: Matched route "app_login". {"route":"app_login","route_parameters":{"_route":"app_login","_controller":"App\\Controller\\SecurityController::login"},"request_uri":"https://192.168.1.16:8004/login","method":"GET"} []
[2021-06-04T14:14:38.562207-04:00] security.INFO: Populated the TokenStorage with an anonymous Token. [] []
[2021-06-04T14:14:39.207858-04:00] request.INFO: Matched route "_wdt". {"route":"_wdt","route_parameters":{"_route":"_wdt","_controller":"web_profiler.controller.profiler::toolbarAction","token":"64bfec"},"request_uri":"https://192.168.1.16:8004/_wdt/64bfec","method":"GET"} []
[2021-06-04T14:14:39.255912-04:00] request.ERROR: Uncaught PHP Exception Symfony\Component\HttpKernel\Exception\NotFoundHttpException: "No route found for "GET /favicon.ico" (from "https://192.168.1.16:8004/login")" at /var/www/symfony/reportes/vendor/symfony/http-kernel/EventListener/RouterListener.php line 136 {"exception":"[object] (Symfony\\Component\\HttpKernel\\Exception\\NotFoundHttpException(code: 0): No route found for \"GET /favicon.ico\" (from \"https://192.168.1.16:8004/login\") at /var/www/symfony/reportes/vendor/symfony/http-kernel/EventListener/RouterListener.php:136)\n[previous exception] [object] (Symfony\\Component\\Routing\\Exception\\ResourceNotFoundException(code: 0): No routes found for \"/favicon.ico/\". at /var/www/symfony/reportes/vendor/symfony/routing/Matcher/Dumper/CompiledUrlMatcherTrait.php:70)"} []
[2021-06-04T14:14:52.580953-04:00] request.INFO: Matched route "app_login". {"route":"app_login","route_parameters":{"_route":"app_login","_controller":"App\\Controller\\SecurityController::login"},"request_uri":"https://192.168.1.16:8004/login","method":"GET"} []
[2021-06-04T14:14:52.590136-04:00] security.INFO: Populated the TokenStorage with an anonymous Token. [] []
[2021-06-04T14:14:52.722719-04:00] request.INFO: Matched route "_wdt". {"route":"_wdt","route_parameters":{"_route":"_wdt","_controller":"web_profiler.controller.profiler::toolbarAction","token":"217e00"},"request_uri":"https://192.168.1.16:8004/_wdt/217e00","method":"GET"} []
[2021-06-04T14:14:53.958161-04:00] request.INFO: Matched route "app_login". {"route":"app_login","route_parameters":{"_route":"app_login","_controller":"App\\Controller\\SecurityController::login"},"request_uri":"https://192.168.1.16:8004/login","method":"GET"} []
[2021-06-04T14:14:53.963413-04:00] security.INFO: Populated the TokenStorage with an anonymous Token. [] []
[2021-06-04T14:14:54.064776-04:00] request.INFO: Matched route "_wdt". {"route":"_wdt","route_parameters":{"_route":"_wdt","_controller":"web_profiler.controller.profiler::toolbarAction","token":"b55de6"},"request_uri":"https://192.168.1.16:8004/_wdt/b55de6","method":"GET"} []
[2021-06-04T14:14:54.628918-04:00] request.INFO: Matched route "app_login". {"route":"app_login","route_parameters":{"_route":"app_login","_controller":"App\\Controller\\SecurityController::login"},"request_uri":"https://192.168.1.16:8004/login","method":"GET"} []
[2021-06-04T14:14:54.645084-04:00] security.INFO: Populated the TokenStorage with an anonymous Token. [] []
[2021-06-04T14:14:54.741822-04:00] request.INFO: Matched route "_wdt". {"route":"_wdt","route_parameters":{"_route":"_wdt","_controller":"web_profiler.controller.profiler::toolbarAction","token":"4461cb"},"request_uri":"https://192.168.1.16:8004/_wdt/4461cb","method":"GET"} []
[2021-06-04T14:14:54.914192-04:00] request.INFO: Matched route "app_login". {"route":"app_login","route_parameters":{"_route":"app_login","_controller":"App\\Controller\\SecurityController::login"},"request_uri":"https://192.168.1.16:8004/login","method":"GET"} []
[2021-06-04T14:14:54.919695-04:00] security.INFO: Populated the TokenStorage with an anonymous Token. [] []
[2021-06-04T14:14:55.059880-04:00] request.INFO: Matched route "_wdt". {"route":"_wdt","route_parameters":{"_route":"_wdt","_controller":"web_profiler.controller.profiler::toolbarAction","token":"ac172b"},"request_uri":"https://192.168.1.16:8004/_wdt/ac172b","method":"GET"} []
[2021-06-04T14:14:55.181191-04:00] request.INFO: Matched route "app_login". {"route":"app_login","route_parameters":{"_route":"app_login","_controller":"App\\Controller\\SecurityController::login"},"request_uri":"https://192.168.1.16:8004/login","method":"GET"} []
[2021-06-04T14:14:55.187907-04:00] security.INFO: Populated the TokenStorage with an anonymous Token. [] []
[2021-06-04T14:14:55.286759-04:00] request.INFO: Matched route "_wdt". {"route":"_wdt","route_parameters":{"_route":"_wdt","_controller":"web_profiler.controller.profiler::toolbarAction","token":"119b16"},"request_uri":"https://192.168.1.16:8004/_wdt/119b16","method":"GET"} []
[2021-06-04T14:14:55.381992-04:00] request.INFO: Matched route "app_login". {"route":"app_login","route_parameters":{"_route":"app_login","_controller":"App\\Controller\\SecurityController::login"},"request_uri":"https://192.168.1.16:8004/login","method":"GET"} []
[2021-06-04T14:14:55.387337-04:00] security.INFO: Populated the TokenStorage with an anonymous Token. [] []
[2021-06-04T14:14:55.493282-04:00] request.INFO: Matched route "_wdt". {"route":"_wdt","route_parameters":{"_route":"_wdt","_controller":"web_profiler.controller.profiler::toolbarAction","token":"429fd0"},"request_uri":"https://192.168.1.16:8004/_wdt/429fd0","method":"GET"} []
[2021-06-04T14:14:55.654017-04:00] request.INFO: Matched route "app_login". {"route":"app_login","route_parameters":{"_route":"app_login","_controller":"App\\Controller\\SecurityController::login"},"request_uri":"https://192.168.1.16:8004/login","method":"GET"} []
[2021-06-04T14:14:55.659546-04:00] security.INFO: Populated the TokenStorage with an anonymous Token. [] []
[2021-06-04T14:14:55.751891-04:00] request.INFO: Matched route "_wdt". {"route":"_wdt","route_parameters":{"_route":"_wdt","_controller":"web_profiler.controller.profiler::toolbarAction","token":"1b94be"},"request_uri":"https://192.168.1.16:8004/_wdt/1b94be","method":"GET"} []
[2021-06-04T14:15:05.125229-04:00] request.INFO: Matched route "app_login". {"route":"app_login","route_parameters":{"_route":"app_login","_controller":"App\\Controller\\SecurityController::login"},"request_uri":"https://192.168.1.16:8004/login","method":"GET"} []
[2021-06-04T14:15:05.138740-04:00] security.INFO: Populated the TokenStorage with an anonymous Token. [] []
[2021-06-04T14:15:05.251329-04:00] request.INFO: Matched route "_wdt". {"route":"_wdt","route_parameters":{"_route":"_wdt","_controller":"web_profiler.controller.profiler::toolbarAction","token":"e69471"},"request_uri":"https://192.168.1.16:8004/_wdt/e69471","method":"GET"} []
[2021-06-04T14:15:05.776409-04:00] request.INFO: Matched route "app_login". {"route":"app_login","route_parameters":{"_route":"app_login","_controller":"App\\Controller\\SecurityController::login"},"request_uri":"https://192.168.1.16:8004/login","method":"GET"} []
[2021-06-04T14:15:05.782674-04:00] security.INFO: Populated the TokenStorage with an anonymous Token. [] []
[2021-06-04T14:15:05.887498-04:00] request.INFO: Matched route "_wdt". {"route":"_wdt","route_parameters":{"_route":"_wdt","_controller":"web_profiler.controller.profiler::toolbarAction","token":"0ba120"},"request_uri":"https://192.168.1.16:8004/_wdt/0ba120","method":"GET"} []
[2021-06-04T14:15:06.121675-04:00] request.INFO: Matched route "app_login". {"route":"app_login","route_parameters":{"_route":"app_login","_controller":"App\\Controller\\SecurityController::login"},"request_uri":"https://192.168.1.16:8004/login","method":"GET"} []
[2021-06-04T14:15:06.128182-04:00] security.INFO: Populated the TokenStorage with an anonymous Token. [] []
[2021-06-04T14:15:06.278243-04:00] request.INFO: Matched route "_wdt". {"route":"_wdt","route_parameters":{"_route":"_wdt","_controller":"web_profiler.controller.profiler::toolbarAction","token":"75ce5e"},"request_uri":"https://192.168.1.16:8004/_wdt/75ce5e","method":"GET"} []
[2021-06-04T14:15:06.447774-04:00] request.INFO: Matched route "app_login". {"route":"app_login","route_parameters":{"_route":"app_login","_controller":"App\\Controller\\SecurityController::login"},"request_uri":"https://192.168.1.16:8004/login","method":"GET"} []
[2021-06-04T14:15:06.453987-04:00] security.INFO: Populated the TokenStorage with an anonymous Token. [] []
[2021-06-04T14:15:06.638178-04:00] request.INFO: Matched route "_wdt". {"route":"_wdt","route_parameters":{"_route":"_wdt","_controller":"web_profiler.controller.profiler::toolbarAction","token":"4d46b6"},"request_uri":"https://192.168.1.16:8004/_wdt/4d46b6","method":"GET"} []
[2021-06-04T14:15:06.697708-04:00] request.INFO: Matched route "app_login". {"route":"app_login","route_parameters":{"_route":"app_login","_controller":"App\\Controller\\SecurityController::login"},"request_uri":"https://192.168.1.16:8004/login","method":"GET"} []
[2021-06-04T14:15:06.701761-04:00] security.INFO: Populated the TokenStorage with an anonymous Token. [] []
[2021-06-04T14:15:06.869331-04:00] request.INFO: Matched route "_wdt". {"route":"_wdt","route_parameters":{"_route":"_wdt","_controller":"web_profiler.controller.profiler::toolbarAction","token":"c118c3"},"request_uri":"https://192.168.1.16:8004/_wdt/c118c3","method":"GET"} []
[2021-06-04T14:15:06.928229-04:00] request.INFO: Matched route "app_login". {"route":"app_login","route_parameters":{"_route":"app_login","_controller":"App\\Controller\\SecurityController::login"},"request_uri":"https://192.168.1.16:8004/login","method":"GET"} []
[2021-06-04T14:15:06.935253-04:00] security.INFO: Populated the TokenStorage with an anonymous Token. [] []
[2021-06-04T14:15:07.037089-04:00] request.INFO: Matched route "_wdt". {"route":"_wdt","route_parameters":{"_route":"_wdt","_controller":"web_profiler.controller.profiler::toolbarAction","token":"0ab394"},"request_uri":"https://192.168.1.16:8004/_wdt/0ab394","method":"GET"} []
[2021-06-04T14:15:07.157750-04:00] request.INFO: Matched route "app_login". {"route":"app_login","route_parameters":{"_route":"app_login","_controller":"App\\Controller\\SecurityController::login"},"request_uri":"https://192.168.1.16:8004/login","method":"GET"} []
[2021-06-04T14:15:07.162863-04:00] security.INFO: Populated the TokenStorage with an anonymous Token. [] []
[2021-06-04T14:15:07.376214-04:00] request.INFO: Matched route "app_login". {"route":"app_login","route_parameters":{"_route":"app_login","_controller":"App\\Controller\\SecurityController::login"},"request_uri":"https://192.168.1.16:8004/login","method":"GET"} []
[2021-06-04T14:15:07.381315-04:00] security.INFO: Populated the TokenStorage with an anonymous Token. [] []
[2021-06-04T14:15:07.573442-04:00] request.INFO: Matched route "_wdt". {"route":"_wdt","route_parameters":{"_route":"_wdt","_controller":"web_profiler.controller.profiler::toolbarAction","token":"3c9197"},"request_uri":"https://192.168.1.16:8004/_wdt/3c9197","method":"GET"} []
[2021-07-08T14:40:03.763233-04:00] request.INFO: Matched route "home". {"route":"home","route_parameters":{"_route":"home","_controller":"App\\Controller\\DashBoardController::index"},"request_uri":"https://192.168.1.16:8004/","method":"GET"} []
[2021-07-08T14:40:03.947242-04:00] security.INFO: Populated the TokenStorage with an anonymous Token. [] []
[2021-07-08T14:40:04.127746-04:00] security.DEBUG: Access denied, the user is not fully authenticated; redirecting to authentication entry point. {"exception":"[object] (Symfony\\Component\\Security\\Core\\Exception\\AccessDeniedException(code: 403): Access Denied. at /var/www/symfony/reportes/vendor/symfony/security-http/Firewall/AccessListener.php:106)"} []
[2021-07-08T14:40:04.129190-04:00] security.DEBUG: Calling Authentication entry point. [] []
[2021-07-08T14:40:04.498997-04:00] request.INFO: Matched route "app_login". {"route":"app_login","route_parameters":{"_route":"app_login","_controller":"App\\Controller\\SecurityController::login"},"request_uri":"https://192.168.1.16:8004/login","method":"GET"} []
[2021-07-08T14:40:04.570187-04:00] security.INFO: Populated the TokenStorage with an anonymous Token. [] []
[2021-07-08T14:40:04.800520-04:00] request.INFO: Matched route "_wdt". {"route":"_wdt","route_parameters":{"_route":"_wdt","_controller":"web_profiler.controller.profiler::toolbarAction","token":"d46c91"},"request_uri":"https://192.168.1.16:8004/_wdt/d46c91","method":"GET"} []
[2021-07-08T14:40:04.963601-04:00] request.ERROR: Uncaught PHP Exception Symfony\Component\HttpKernel\Exception\NotFoundHttpException: "No route found for "GET /favicon.ico" (from "https://192.168.1.16:8004/login")" at /var/www/symfony/reportes/vendor/symfony/http-kernel/EventListener/RouterListener.php line 136 {"exception":"[object] (Symfony\\Component\\HttpKernel\\Exception\\NotFoundHttpException(code: 0): No route found for \"GET /favicon.ico\" (from \"https://192.168.1.16:8004/login\") at /var/www/symfony/reportes/vendor/symfony/http-kernel/EventListener/RouterListener.php:136)\n[previous exception] [object] (Symfony\\Component\\Routing\\Exception\\ResourceNotFoundException(code: 0): No routes found for \"/favicon.ico/\". at /var/www/symfony/reportes/vendor/symfony/routing/Matcher/Dumper/CompiledUrlMatcherTrait.php:70)"} []
[2021-07-08T14:40:17.968934-04:00] request.INFO: Matched route "app_login". {"route":"app_login","route_parameters":{"_route":"app_login","_controller":"App\\Controller\\SecurityController::login"},"request_uri":"https://192.168.1.16:8004/login","method":"POST"} []
[2021-07-08T14:40:18.327863-04:00] doctrine.DEBUG: SELECT t0.id AS id_1, t0.email AS email_2, t0.roles AS roles_3, t0.password AS password_4, t0.nombre AS nombre_5, t0.apellidos AS apellidos_6, t0.activo AS activo_7, t0.fecha_alta AS fecha_alta_8, t0.fecha_update AS fecha_update_9, t0.telef AS telef_10, t0.descripcion AS descripcion_11, t0.ocupacion AS ocupacion_12, t0.usertype AS usertype_13 FROM user t0 WHERE t0.email = ? LIMIT 1 ["yuriang"] []
[2021-07-08T14:40:18.572895-04:00] php.DEBUG: Warning: ldap_bind(): Unable to bind to server: Invalid credentials {"exception":{"Symfony\\Component\\ErrorHandler\\Exception\\SilencedErrorContext":{"severity":2,"file":"/var/www/symfony/reportes/vendor/symfony/ldap/Adapter/ExtLdap/Connection.php","line":72,"trace":[{"file":"/var/www/symfony/reportes/vendor/symfony/ldap/Ldap.php","line":40,"function":"bind","class":"Symfony\\Component\\Ldap\\Adapter\\ExtLdap\\Connection","type":"->"}],"count":1}}} []
[2021-07-08T14:40:18.575729-04:00] doctrine.DEBUG: SELECT t0.id AS id_1, t0.email AS email_2, t0.roles AS roles_3, t0.password AS password_4, t0.nombre AS nombre_5, t0.apellidos AS apellidos_6, t0.activo AS activo_7, t0.fecha_alta AS fecha_alta_8, t0.fecha_update AS fecha_update_9, t0.telef AS telef_10, t0.descripcion AS descripcion_11, t0.ocupacion AS ocupacion_12, t0.usertype AS usertype_13 FROM user t0 WHERE t0.email = ? LIMIT 1 ["yuriang"] []
[2021-07-08T14:40:18.577580-04:00] security.INFO: Authentication request failed. {"exception":"[object] (Symfony\\Component\\Security\\Core\\Exception\\BadCredentialsException(code: 0): Bad credentials. at /var/www/symfony/reportes/vendor/symfony/security-core/Authentication/Provider/UserAuthenticationProvider.php:67)\n[previous exception] [object] (Symfony\\Component\\Security\\Core\\Exception\\UsernameNotFoundException(code: 0): There is no user with name \"yuriang\". at /var/www/symfony/reportes/vendor/symfony/security-core/User/ChainUserProvider.php:62)"} []
[2021-07-08T14:40:18.577871-04:00] security.DEBUG: Authentication failure, redirect triggered. {"failure_path":"app_login"} []
[2021-07-08T14:40:18.646562-04:00] request.INFO: Matched route "app_login". {"route":"app_login","route_parameters":{"_route":"app_login","_controller":"App\\Controller\\SecurityController::login"},"request_uri":"https://192.168.1.16:8004/login","method":"GET"} []
[2021-07-08T14:40:18.652555-04:00] security.INFO: Populated the TokenStorage with an anonymous Token. [] []
[2021-07-08T14:40:18.865813-04:00] request.INFO: Matched route "_wdt". {"route":"_wdt","route_parameters":{"_route":"_wdt","_controller":"web_profiler.controller.profiler::toolbarAction","token":"e79ec4"},"request_uri":"https://192.168.1.16:8004/_wdt/e79ec4","method":"GET"} []
[2021-07-09T11:09:18.200170-04:00] php.DEBUG: Warning: include(/var/www/symfony/reportes/var/cache/de_/App_KernelDevDebugContainer.php): failed to open stream: No such file or directory {"exception":{"Symfony\\Component\\ErrorHandler\\Exception\\SilencedErrorContext":{"severity":2,"file":"/var/www/symfony/reportes/vendor/symfony/http-kernel/Kernel.php","line":469,"trace":[{"file":"/var/www/symfony/reportes/vendor/symfony/http-kernel/Kernel.php","line":469,"function":"include"}],"count":1}}} []
[2021-07-09T11:09:18.221497-04:00] php.DEBUG: Warning: include(): Failed opening '/var/www/symfony/reportes/var/cache/de_/App_KernelDevDebugContainer.php' for inclusion (include_path='.:/usr/share/php') [] []
[2021-07-09T11:19:43.499406-04:00] request.INFO: Matched route "home". {"route":"home","route_parameters":{"_route":"home","_controller":"App\\Controller\\DashBoardController::index"},"request_uri":"https://192.168.1.16:8004/","method":"GET"} []
[2021-07-09T11:19:43.534310-04:00] security.INFO: Populated the TokenStorage with an anonymous Token. [] []
[2021-07-09T11:19:43.583347-04:00] security.DEBUG: Access denied, the user is not fully authenticated; redirecting to authentication entry point. {"exception":"[object] (Symfony\\Component\\Security\\Core\\Exception\\AccessDeniedException(code: 403): Access Denied. at /var/www/symfony/reportes/vendor/symfony/security-http/Firewall/AccessListener.php:106)"} []
[2021-07-09T11:19:43.584130-04:00] security.DEBUG: Calling Authentication entry point. [] []
[2021-07-09T11:19:43.707665-04:00] request.INFO: Matched route "app_login". {"route":"app_login","route_parameters":{"_route":"app_login","_controller":"App\\Controller\\SecurityController::login"},"request_uri":"https://192.168.1.16:8004/login","method":"GET"} []
[2021-07-09T11:19:43.723045-04:00] security.INFO: Populated the TokenStorage with an anonymous Token. [] []
[2021-07-09T11:19:43.882070-04:00] request.INFO: Matched route "_wdt". {"route":"_wdt","route_parameters":{"_route":"_wdt","_controller":"web_profiler.controller.profiler::toolbarAction","token":"918a00"},"request_uri":"https://192.168.1.16:8004/_wdt/918a00","method":"GET"} []
[2021-07-09T11:19:43.964114-04:00] request.ERROR: Uncaught PHP Exception Symfony\Component\HttpKernel\Exception\NotFoundHttpException: "No route found for "GET /favicon.ico" (from "https://192.168.1.16:8004/login")" at /var/www/symfony/reportes/vendor/symfony/http-kernel/EventListener/RouterListener.php line 136 {"exception":"[object] (Symfony\\Component\\HttpKernel\\Exception\\NotFoundHttpException(code: 0): No route found for \"GET /favicon.ico\" (from \"https://192.168.1.16:8004/login\") at /var/www/symfony/reportes/vendor/symfony/http-kernel/EventListener/RouterListener.php:136)\n[previous exception] [object] (Symfony\\Component\\Routing\\Exception\\ResourceNotFoundException(code: 0): No routes found for \"/favicon.ico/\". at /var/www/symfony/reportes/vendor/symfony/routing/Matcher/Dumper/CompiledUrlMatcherTrait.php:70)"} []
